# Hola mundo equivalente al Git

Desde el tema de Numpy, este archivo se convirtió en un equivalente a al documentos de ejemplos de clase.

# Tema 1. Conceptos Basicos de Python.

# Tema 2. Numpy

* **Ejercicio 1:**


Hacer una matriz de 8 x 8 con numeros enteros consecutivos empezando en 1. Llenado por filas (1,2,3,4...).

In [1]:
import numpy as np

In [2]:
alpha = np.arange(1,65,1)

In [3]:
beta = np.reshape(alpha,(8,8))

#### **Ejercicio 2:**

* i. Hacer una matriz de 8 x 8 con numeros enteros consecutivos empezando en 1. Llenado por columnas.

* ii. reemplazar los elementos que tengan al menos un 3 por -99.

In [4]:
alpha = beta
beta = np.transpose(beta)

In [5]:
alpha

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [6]:
beta

array([[ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64]])

In [7]:
for i in range(8):
    for j in range(8):
        epsilon = str(beta[i][j])
        omega = epsilon.find('3')
        if (omega != -1):
            beta[i][j] = -99
            

In [8]:
beta

array([[  1,   9,  17,  25, -99,  41,  49,  57],
       [  2,  10,  18,  26, -99,  42,  50,  58],
       [-99,  11,  19,  27, -99, -99,  51,  59],
       [  4,  12,  20,  28, -99,  44,  52,  60],
       [  5, -99,  21,  29, -99,  45, -99,  61],
       [  6,  14,  22, -99, -99,  46,  54,  62],
       [  7,  15, -99, -99, -99,  47,  55, -99],
       [  8,  16,  24, -99,  40,  48,  56,  64]])

In [9]:
a = 'alpha'
a.find('@')


-1

#### Ejercicio 3: 
* i. Reproducir la matriz B:
[[0.4 0.41 0.42 0.43 0.44] 
[0.45 0.46 0.47 0.48 0.49] ,
[0.5 0.51 0.52 0.53 0.54]
[0.55 0.56 0.57 0.58 0.59]
[0.6 0.61 0.62 0.63 0.64]
[0.65 0.66 0.67 0.68 0.69]
[0.7 0.71 0.72 0.73 0.74]
[0.75 0.76 0.77 0.78 0.79]]

* ii. Unir B con el resultado del ejercicio anterior 2.ii para obtener una matriz de 8 lineas y 13 columnas.

* iii. Agregar una linea al final con el promedio de cada columna

* iv. Agregar una columna al final con el valor maximo de cada fila

* v. Guardar en un archivo.

In [10]:
#i
B = np.arange(0.4,0.8,0.01)
B

array([0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ,
       0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61,
       0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72,
       0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79])

In [11]:
B = np.reshape(B,(8,5))

In [12]:
B

array([[0.4 , 0.41, 0.42, 0.43, 0.44],
       [0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54],
       [0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64],
       [0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74],
       [0.75, 0.76, 0.77, 0.78, 0.79]])

In [13]:
#ii
beta

array([[  1,   9,  17,  25, -99,  41,  49,  57],
       [  2,  10,  18,  26, -99,  42,  50,  58],
       [-99,  11,  19,  27, -99, -99,  51,  59],
       [  4,  12,  20,  28, -99,  44,  52,  60],
       [  5, -99,  21,  29, -99,  45, -99,  61],
       [  6,  14,  22, -99, -99,  46,  54,  62],
       [  7,  15, -99, -99, -99,  47,  55, -99],
       [  8,  16,  24, -99,  40,  48,  56,  64]])

In [14]:
Bbeta = np.append(B,beta,axis=1)


In [15]:
np.shape(Bbeta)

(8, 13)

In [16]:
Bbeta

array([[  0.4 ,   0.41,   0.42,   0.43,   0.44,   1.  ,   9.  ,  17.  ,
         25.  , -99.  ,  41.  ,  49.  ,  57.  ],
       [  0.45,   0.46,   0.47,   0.48,   0.49,   2.  ,  10.  ,  18.  ,
         26.  , -99.  ,  42.  ,  50.  ,  58.  ],
       [  0.5 ,   0.51,   0.52,   0.53,   0.54, -99.  ,  11.  ,  19.  ,
         27.  , -99.  , -99.  ,  51.  ,  59.  ],
       [  0.55,   0.56,   0.57,   0.58,   0.59,   4.  ,  12.  ,  20.  ,
         28.  , -99.  ,  44.  ,  52.  ,  60.  ],
       [  0.6 ,   0.61,   0.62,   0.63,   0.64,   5.  , -99.  ,  21.  ,
         29.  , -99.  ,  45.  , -99.  ,  61.  ],
       [  0.65,   0.66,   0.67,   0.68,   0.69,   6.  ,  14.  ,  22.  ,
        -99.  , -99.  ,  46.  ,  54.  ,  62.  ],
       [  0.7 ,   0.71,   0.72,   0.73,   0.74,   7.  ,  15.  , -99.  ,
        -99.  , -99.  ,  47.  ,  55.  , -99.  ],
       [  0.75,   0.76,   0.77,   0.78,   0.79,   8.  ,  16.  ,  24.  ,
        -99.  ,  40.  ,  48.  ,  56.  ,  64.  ]])

In [32]:
#iii Agregar una linea al final con el promedio de cada columna
Omicron = np.array([])
for i in range(13):
    omicron = np.mean(Bbeta[:,i])
    Omicron = np.append(Omicron,omicron)


In [52]:
Bbeta[1,:]

array([  0.45,   0.46,   0.47,   0.48,   0.49,   2.  ,  10.  ,  18.  ,
        26.  , -99.  ,  42.  ,  50.  ,  58.  ])

In [53]:
Bbeta[1][:]

array([  0.45,   0.46,   0.47,   0.48,   0.49,   2.  ,  10.  ,  18.  ,
        26.  , -99.  ,  42.  ,  50.  ,  58.  ])

In [51]:
Bbeta[:][1]

array([  0.45,   0.46,   0.47,   0.48,   0.49,   2.  ,  10.  ,  18.  ,
        26.  , -99.  ,  42.  ,  50.  ,  58.  ])

In [54]:
#iii Agregar una linea al final con el promedio de cada columna
Omicron2 = np.array([])
for i in range(13):
    omicron2 = np.mean(Bbeta[i][:])
    Omicron2 = np.append(Omicron2,omicron2)

IndexError: index 8 is out of bounds for axis 0 with size 8

In [18]:
Omicron

array([  0.575,   0.585,   0.595,   0.605,   0.615,  -8.25 ,  -1.5  ,
         5.25 , -20.25 , -81.625,  26.75 ,  33.5  ,  40.25 ])

In [19]:
Bbeta2=np.vstack([Bbeta,Omicron])

In [20]:
Bbeta2

array([[  0.4  ,   0.41 ,   0.42 ,   0.43 ,   0.44 ,   1.   ,   9.   ,
         17.   ,  25.   , -99.   ,  41.   ,  49.   ,  57.   ],
       [  0.45 ,   0.46 ,   0.47 ,   0.48 ,   0.49 ,   2.   ,  10.   ,
         18.   ,  26.   , -99.   ,  42.   ,  50.   ,  58.   ],
       [  0.5  ,   0.51 ,   0.52 ,   0.53 ,   0.54 , -99.   ,  11.   ,
         19.   ,  27.   , -99.   , -99.   ,  51.   ,  59.   ],
       [  0.55 ,   0.56 ,   0.57 ,   0.58 ,   0.59 ,   4.   ,  12.   ,
         20.   ,  28.   , -99.   ,  44.   ,  52.   ,  60.   ],
       [  0.6  ,   0.61 ,   0.62 ,   0.63 ,   0.64 ,   5.   , -99.   ,
         21.   ,  29.   , -99.   ,  45.   , -99.   ,  61.   ],
       [  0.65 ,   0.66 ,   0.67 ,   0.68 ,   0.69 ,   6.   ,  14.   ,
         22.   , -99.   , -99.   ,  46.   ,  54.   ,  62.   ],
       [  0.7  ,   0.71 ,   0.72 ,   0.73 ,   0.74 ,   7.   ,  15.   ,
        -99.   , -99.   , -99.   ,  47.   ,  55.   , -99.   ],
       [  0.75 ,   0.76 ,   0.77 ,   0.78 ,   0.79 ,   8.   , 

In [21]:
Sigma = np.array([])
for i in range(9):
    maxcow = max(Bbeta2[i,:])
    Sigma= np.append(Sigma,maxcow)

In [22]:
Sigma.transpose()

array([57.  , 58.  , 59.  , 60.  , 61.  , 62.  , 55.  , 64.  , 40.25])

In [23]:
Bbeta3 = np.append(Bbeta2, np.array([Sigma]).transpose(),axis=1)

In [24]:
Bbeta3

array([[  0.4  ,   0.41 ,   0.42 ,   0.43 ,   0.44 ,   1.   ,   9.   ,
         17.   ,  25.   , -99.   ,  41.   ,  49.   ,  57.   ,  57.   ],
       [  0.45 ,   0.46 ,   0.47 ,   0.48 ,   0.49 ,   2.   ,  10.   ,
         18.   ,  26.   , -99.   ,  42.   ,  50.   ,  58.   ,  58.   ],
       [  0.5  ,   0.51 ,   0.52 ,   0.53 ,   0.54 , -99.   ,  11.   ,
         19.   ,  27.   , -99.   , -99.   ,  51.   ,  59.   ,  59.   ],
       [  0.55 ,   0.56 ,   0.57 ,   0.58 ,   0.59 ,   4.   ,  12.   ,
         20.   ,  28.   , -99.   ,  44.   ,  52.   ,  60.   ,  60.   ],
       [  0.6  ,   0.61 ,   0.62 ,   0.63 ,   0.64 ,   5.   , -99.   ,
         21.   ,  29.   , -99.   ,  45.   , -99.   ,  61.   ,  61.   ],
       [  0.65 ,   0.66 ,   0.67 ,   0.68 ,   0.69 ,   6.   ,  14.   ,
         22.   , -99.   , -99.   ,  46.   ,  54.   ,  62.   ,  62.   ],
       [  0.7  ,   0.71 ,   0.72 ,   0.73 ,   0.74 ,   7.   ,  15.   ,
        -99.   , -99.   , -99.   ,  47.   ,  55.   , -99.   ,  55.   ],

In [25]:
np.savetxt('datos.tsv', Bbeta3, delimiter='\t', fmt='%.3f')