# Numpy

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4,])

lista = ['a', 'b', 'c']
b = np.array(lista)

print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [2]:
c = np.array([1, 2, 9, 3, 4])
print(c.dtype)

int32


In [3]:
c1 = np.array([1.1 , 2, 9, 3, 4])
print(c1.dtype)

float64


In [4]:
c2 = np.array(['1',2,3,4,5,6])
print(c2.dtype)

<U11


In [16]:
#Array de dos dimensiones

d2 = np.array([[1, 2, 3, 4, 5], [1,2,3,4,5]])

print(d2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
d2.insert()

In [24]:
alpha = np.zeros((3,2))

In [29]:
alpha[2][0]=1

In [30]:
print(alpha)

[[0. 0.]
 [0. 1.]
 [1. 1.]]


In [23]:
np.ones((5,5,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])